language: python
python:
  - "3.6"
services:
  - mongodb
before_install:
  - pip install --upgrade pip
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install --upgrade pytest
  - pip install cltk
  - mkdir -p $HOME/cltk_data/greek/model
  - mkdir -p $HOME/cltk_data/latin/model
  - git clone https://github.com/cltk/greek_models_cltk $HOME/cltk_data/greek/model/greek_models_cltk
  - git clone https://github.com/cltk/latin_models_cltk $HOME/cltk_data/latin/model/latin_models_cltk
install: pip install .
script: pytest
